### ISSUE TITLE
Problem with data object info

### ISSUE THREAD

**Issue by fsbarros98** [Joeclinton1/google-images-download#30]
![image](https://user-images.githubusercontent.com/51003517/205890197-3e06eb85-7051-412c-b63b-222a016a715c.png)
the info seems to be coming in position 22 instead of 9 or 11, both of them are empty

**Comment by diveaire** [comment]
same problem,
when i try to download i got this error:
```
Evaluating...
Starting Download...
'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "google_images_download.py", line 1178, in <module>
    main()
  File "google_images_download.py", line 1166, in main
    paths, errors = response.download(arguments)  # wrapping response in a variable just for consistency
  File "google_images_download.py", line 979, in download
    paths, errors = self.download_executor(arguments)
  File "google_images_download.py", line 1119, in download_executor
    arguments)  # get all image items and download images
  File "google_images_download.py", line 906, in _get_all_items
    object['image_link'], object['image_format'], main_directory, dir_name, count,
TypeError: 'NoneType' object is not subscriptable
```
Any idea how to fix it ??

**Comment by fsbarros98** [comment]
I fixed it by changing line 407 in google_images_download.py from `info = data[11] ` to `info = data[22]`, but I advise debugging within this function to verify if this will work for you

**Comment by marianoig4** [comment]
Is no working for me. Even changing the 407 line....

**Comment by nikukyugamer** [comment]
How about not `info = data[22]` but `info = data[23]`?
However, it is true that this is only a temporary fix.

cf. https://github.com/Joeclinton1/google-images-download/pull/34
