### ISSUE TITLE
JSON output of Google API changed again I think

### ISSUE THREAD

**Issue by eamonnkenny** [Joeclinton1/google-images-download#31]
Hi Joe, 

I think they changed the google API again. Getting None errors returned from any attempted download. I presume we've to dig into their output again to find a fix.

**Comment by eamonnkenny** [comment]
the error is arising inside the format_object function because the try except returns an exception which is None. Might be a good idea to not just print(e) but instead do something like print( "Error in format_object:", e )

**Comment by eamonnkenny** [comment]
Because the info assignment has failed, the 5th item referencing the info values fails in the try function, hence causing the error that we see on screen

**Comment by eamonnkenny** [comment]
Found the fix Joe, turns out that if you change info = data[11] to info = data[22] it will all start working again.

**Comment by greg-oz** [comment]
Works for me as well - Thanks

**Comment by Charlweed** [comment]
Future readers,  for branch "patch-1"  commit e91e6a38ad654877f59edc7894822f5319d75df1, the line to edit is
file: google_images_download/google_images_download.py
method: format_object
line: 407
And works on Google Image Search for Tuesday, December 27, 2022 11:31:19 AM
I changed "info = data[11]" to "info = data[22]" and had success :)

**Comment by websonder** [comment]
its stop again, is there any solution so i can run it again?

**Comment by DenimPauel** [comment]
on Jan. 9, 2023
I changed "info = data[11]" to "info = data[23]" and had success.

**Comment by websonder** [comment]
Thanks Its working

**Comment by gwonhong** [comment]
January 17, 2023 03:03:44 AM

"info = data[11]" to "info = data[22]"

doesn't work. It worked until last week as I remember.

Error message starts with 
'bool' object is not subscriptable

And just read the answer from @DenimPauel 
"info = data[11]" to "info = data[**23**]"
works!
Thanks to @DenimPauel

**Comment by gipinze** [comment]
> January 17, 2023 03:03:44 AM
> 
> "info = data[11]" to "info = data[22]"
> 
> doesn't work. It worked until last week as I remember.
> 
> Error message starts with 'bool' object is not subscriptable
> 
> And just read the answer from @DenimPauel "info = data[11]" to "info = data[**23**]" works! Thanks to @DenimPauel

Yes, info = data[23] works

16th January 2023

**Comment by mrclean789** [comment]
Did it change again? Not working now.

**Comment by eamonnkenny** [comment]
Is the command line now superslow? 
I ran the following and its taking an age to run:

googleimagesdownload -l 10 -r labeled-for-reuse -k pepper -f jpg

**Comment by Mr-Philo** [comment]
Thanks all for sharing this solution!

Until now (2023/02/11), changing `info = data[11]` to `info = data[23]` still works for me 👍

**Comment by spacewalkingninja** [comment]
Works here too! This should be updated to the main git tho :(

**Comment by trevorgribble** [comment]
Bumping again today (March 22), anyone else affected?

**Comment by DenimPauel** [comment]
change 
from "info = data[9]"
to "info = data[25]"
on line 405 or 407 in google_images_download.py.

or ... How about this?
https://github.com/Joeclinton1/google-images-download/pull/33/commits/bb22871df27188302c73fdf8aa8faf1df9ae0839
this could search data[xx] maybe in the feature too.

Mar. 23, 2023.

**Comment by eamonnkenny** [comment]
So, we are at the previous bug again... 3rd time fixing it. This now is a better fix, and would have fixed the code 3 times without having to definte which item gives the correct value of info:

        if info is None:
            # EK
            #info = data[11]
            for item in data:
               if type( item ) == dict:
                   info = item

basically what I'm doing is looking at all values of data and seeing which one is the dictionary. When we find it this is what info is set to. It works. And it would have worked for data[22] which occurred about 6 months ago. This then changed to data[23] and now the issue is that info = data[25]. We should just use my new fix. At least if there is one available directory the code can find the value of info itself.

**Comment by trevorgribble** [comment]
@eamonnkenny great call, working smooth again, thank you very much.

**Comment by mrclean789** [comment]
None of the fixes seem to be working anymore. Any solutions?

**Comment by eamonnkenny** [comment]
Hi MrClean,

I think that it was rolled back to a really old version. You will need to
implement my fix as described in issue #31 to replace lines 406 and 407
which currently are wrong:

        if info is None:
            info = data[11]

in google_image_download.py. My fix in issue #31 should just work. I'm not
an editor of the code, so I can't fix the git repository.

Best Regards,
Eamonn Kenny

**Comment by mrclean789** [comment]
Thank you Eamonn, yes it works now. I'm actually running this again on a new machine and found out I had to install certificates :D

**Comment by websonder** [comment]
hi this is my config
# Format the object in readable format
    def format_object(self, object):
        data = object[1]
        main = data[3]
        info = data[25]
        if info is None:
            info = data[11]
        formatted_object = {}
        try:
    
i am getting error, could you please help me to solve this
Item no.: 575 --> Item name = Anyk Napja 2023
Evaluating...
-1
Image objects data unpacking failed. Please leave a comment with the above error at https://github.com/Joeclinton1/google-images-download/pull/26
Traceback (most recent call last):
  File "/home/usethis/script1.py", line 1380, in <module>
    main()
  File "/home/usethis/script1.py", line 1367, in main
    paths, errors = response.download(arguments)  # wrapping response in a variable just for consistency
  File "/home/usethis/script1.py", line 1007, in download
    paths, errors = self.download_executor(arguments)
  File "/home/usethis/script1.py", line 1143, in download_executor
    images, tabs = self.download_page(url)  # download page
TypeError: cannot unpack non-iterable NoneType object

**Comment by rotaugenlaubfrosch** [comment]
I have 

```
 def format_object(self, object):
        data = object[1]
        main = data[3]
        info = data[25]
        if info is None:
            for item in data:
                if type( item ) == dict:
                    info = item
        formatted_object = {}
...
```
And sadly I get:
`Image objects data unpacking failed. Please leave a comment with the above error at ....`

**Comment by trevorgribble** [comment]
> I have
> 
> ```
>  def format_object(self, object):
>         data = object[1]
>         main = data[3]
>         info = data[25]
>         if info is None:
>             for item in data:
>                 if type( item ) == dict:
>                     info = item
>         formatted_object = {}
> ...
> ```
> 
> And sadly I get: `Image objects data unpacking failed. Please leave a comment with the above error at ....`

Receiving same output, did some digging and it appears the issue is upstream from this format_object function.

Specifically, in the _extract_data_pack function:

```
def _extract_data_pack(self, page) function, 
           start_line = page.find("AF_initDataCallback({key: \\'ds:1\\'") - 10
```
is returning -11 (meaning that page.find is returning -1, so we are not finding the desired term.  Everything from then on is basically coming up with no data.

So it's seems that the respData returned from:
```

                req = urllib.request.Request(url, headers=headers)
                resp = urllib.request.urlopen(req)
                respData = str(resp.read())
```
                
Has changed quite a bit that the _extract_data_pack function is no longer functional.

**Comment by websonder** [comment]
please let me know if someone found any solution for this, i really need this
